key_pair_name       = "franquicia-key"
ecr_repository_url  = "051826737831.dkr.ecr.us-east-1.amazonaws.com/franquicias-api-ecr"
ami_id              = "ami-0fc5d935ebf8bc3bc"
docker_image_tag    = "latest"
region         = "us-east-1"
instance_type  = "t2.micro"
