name: Deploy API to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set AWS region
        run: echo "AWS_REGION=us-east-1" >> $GITHUB_ENV  # Asegúrate de usar tu región correcta

      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: private
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Build Docker image
        run: |
          docker build -t franquicia-api .

      - name: Tag Docker image
        run: |
          docker tag franquicia-api:latest ${{ secrets.ECR_REPOSITORY_URI }}:latest

      - name: Push to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

      - name: Deploy API to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Login to ECR
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 051826737831.dkr.ecr.us-east-1.amazonaws.com

            # Pull latest image
            docker pull 051826737831.dkr.ecr.us-east-1.amazonaws.com/franquicias-api-ecr:latest

            # Stop and remove existing container if exists
            docker stop franquicia-api || true
            docker rm franquicia-api || true

            # Run new container
            docker run -d -p 8080:8080 --name franquicia-api 051826737831.dkr.ecr.us-east-1.amazonaws.com/franquicias-api-ecr:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.ECR_REPOSITORY_URI }}:latest
            docker stop franquicia-api || true && docker rm franquicia-api || true
            docker run -d -p 8080:8080 --name franquicia-api ${{ secrets.ECR_REPOSITORY_URI }}:latest
