name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to ECR
        run: |
          docker build -t franquicias-api-ecr .
          docker tag franquicias-api-ecr:latest 051826737831.dkr.ecr.us-east-1.amazonaws.com/franquicias-api-ecr:latest
          docker push 051826737831.dkr.ecr.us-east-1.amazonaws.com/franquicias-api-ecr:latest

      - name: SSH to EC2 and deploy container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo ">>> Iniciando login a ECR desde EC2"
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_REGION=us-east-1

            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 051826737831.dkr.ecr.us-east-1.amazonaws.com

            echo ">>> Extrayendo nueva imagen"
            docker pull 051826737831.dkr.ecr.us-east-1.amazonaws.com/franquicias-api-ecr:latest

            echo ">>> Deteniendo contenedor previo (si existe)"
            docker stop franquicia-api || true
            docker rm franquicia-api || true

            echo ">>> Iniciando nuevo contenedor"
            docker run -d -p 8080:8080 --name franquicia-api 051826737831.dkr.ecr.us-east-1.amazonaws.com/franquicias-api-ecr:latest
